# Generated by Django 5.1.4 on 2025-11-30 11:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wedding_planner', '0012_add_table_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting/Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('priority_order', models.PositiveIntegerField(default=50, help_text='Numeric priority for ordering (higher = more important)')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_milestone', models.BooleanField(default=False, help_text='Mark as a major milestone in wedding planning')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of list')),
                ('external_url', models.URLField(blank=True, help_text='Link to external resource (Pinterest, vendor site, etc.)', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent task if this is a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo_list_wedding.todo')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='wedding_planner.wedding')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-priority_order', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='todo_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('inspiration', 'Inspiration'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo_list_wedding.todo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo Attachment',
                'verbose_name_plural': 'Todo Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the category', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'camera', 'utensils', 'music')", max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_categories', to='wedding_planner.wedding')),
            ],
            options={
                'verbose_name': 'Todo Category',
                'verbose_name_plural': 'Todo Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('wedding', 'name')},
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todo_list_wedding.todocategory'),
        ),
        migrations.CreateModel(
            name='TodoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='todo_list_wedding.todo')),
            ],
            options={
                'verbose_name': 'Todo Checklist Item',
                'verbose_name_plural': 'Todo Checklist Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_comments', to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo_list_wedding.todo')),
            ],
            options={
                'verbose_name': 'Todo Comment',
                'verbose_name_plural': 'Todo Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(help_text='Category name to create/use when applying template', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeline_position', models.CharField(choices=[('12_plus', '12+ Months Before'), ('9_12', '9-12 Months Before'), ('6_9', '6-9 Months Before'), ('4_6', '4-6 Months Before'), ('2_4', '2-4 Months Before'), ('1_2', '1-2 Months Before'), ('2_4_weeks', '2-4 Weeks Before'), ('1_week', 'Final Week'), ('day_of', 'Wedding Day'), ('post', 'After Wedding')], default='6_9', max_length=20)),
                ('days_before_wedding', models.PositiveIntegerField(blank=True, help_text='Exact days before wedding (overrides timeline_position for due date calc)', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_milestone', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('checklist_items', models.JSONField(blank=True, default=list, help_text='List of checklist items: [{"title": "Item 1"}, {"title": "Item 2"}]')),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_templates', to='wedding_planner.wedding')),
            ],
            options={
                'verbose_name': 'Todo Template',
                'verbose_name_plural': 'Todo Templates',
                'ordering': ['timeline_position', 'order'],
            },
        ),
    ]
