# Generated by Django 5.1.4 on 2025-10-17 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="prefer_not_to_say",
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
            ],
            options={
                "verbose_name": "gender",
                "verbose_name_plural": "genders",
            },
        ),
        migrations.RemoveField(
            model_name="guestpartner",
            name="guest",
        ),
        migrations.DeleteModel(
            name="Child",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="GuestPartner",
        ),
    ]
