# Generated by Django 5.1.4 on 2025-11-29 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_planner", "0004_guestsmax"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Restriction Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon identifier", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Dietary Restriction",
                "verbose_name_plural": "Dietary Restrictions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MealChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Meal Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("meat", "Meat"),
                            ("fish", "Fish"),
                            ("poultry", "Poultry"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("kids", "Kids Menu"),
                        ],
                        max_length=20,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Currently Available"
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum servings available (leave blank for unlimited)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Choice",
                "verbose_name_plural": "Meal Choices",
                "ordering": ["meal_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Table Number"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional table name (e.g., 'Rose Table', 'Family Table')",
                        max_length=100,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Seating Capacity"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location description (e.g., 'Near dance floor', 'By the garden')",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Special notes about this table"
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="VIP/Family Table"),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["table_number"],
            },
        ),
        migrations.CreateModel(
            name="WeddingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Our Wedding", max_length=200, verbose_name="Event Name"
                    ),
                ),
                ("event_date", models.DateField(verbose_name="Wedding Date")),
                ("ceremony_time", models.TimeField(verbose_name="Ceremony Start Time")),
                (
                    "reception_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Reception Start Time"
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=300, verbose_name="Venue Name"),
                ),
                ("venue_address", models.TextField(verbose_name="Venue Address")),
                ("venue_city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "venue_map_url",
                    models.URLField(blank=True, verbose_name="Google Maps URL"),
                ),
                (
                    "reception_venue_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Reception Venue Name"
                    ),
                ),
                (
                    "reception_venue_address",
                    models.TextField(
                        blank=True, verbose_name="Reception Venue Address"
                    ),
                ),
                (
                    "dress_code",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("smart_casual", "Smart Casual"),
                            ("cocktail", "Cocktail"),
                            ("formal", "Formal / Black Tie Optional"),
                            ("black_tie", "Black Tie"),
                            ("white_tie", "White Tie"),
                            ("themed", "Themed"),
                        ],
                        default="formal",
                        max_length=20,
                        verbose_name="Dress Code",
                    ),
                ),
                (
                    "dress_code_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about dress code (e.g., color theme, outdoor venue)",
                    ),
                ),
                ("rsvp_deadline", models.DateField(verbose_name="RSVP Deadline")),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, help_text="Parking info, accessibility notes, etc."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active event is displayed to guests"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wedding Event",
                "verbose_name_plural": "Wedding Events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="GuestMealSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergies",
                    models.TextField(
                        blank=True, help_text="Specific allergies or food restrictions"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, help_text="Any other meal-related requests"
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guests",
                        to="wedding_planner.dietaryrestriction",
                    ),
                ),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_selection",
                        to="wedding_planner.guest",
                    ),
                ),
                (
                    "meal_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_selections",
                        to="wedding_planner.mealchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Meal Selection",
                "verbose_name_plural": "Guest Meal Selections",
            },
        ),
        migrations.CreateModel(
            name="SeatingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional specific seat number at the table",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about seating (e.g., 'Needs accessible seating')",
                    ),
                ),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_assignment",
                        to="wedding_planner.guest",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_assignments",
                        to="wedding_planner.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seating Assignment",
                "verbose_name_plural": "Seating Assignments",
                "ordering": ["table__table_number", "seat_number"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("seat_number__isnull", False)),
                        fields=("table", "seat_number"),
                        name="unique_seat_at_table",
                    )
                ],
            },
        ),
    ]
