# Generated by Django 5.1.4 on 2025-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0009_add_guest_type_and_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='dietary restrictions'),
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='guest',
            name='plus_one_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='plus one name'),
        ),
    ]
