# Generated by Django 5.1.4 on 2025-11-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0010_guest_address_guest_dietary_restrictions_guest_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingassignment',
            name='attendee_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('plus_one', 'Plus One'), ('child', 'Child')], default='guest', max_length=20, verbose_name='Attendee Type'),
        ),
        migrations.AddField(
            model_name='seatingassignment',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Link to child if this is a child assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignment', to='wedding_planner.child'),
        ),
        migrations.AlterField(
            model_name='seatingassignment',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments', to='wedding_planner.guest'),
        ),
        migrations.AddConstraint(
            model_name='seatingassignment',
            constraint=models.UniqueConstraint(fields=('guest', 'attendee_type'), name='unique_guest_attendee_type'),
        ),
        migrations.AddConstraint(
            model_name='seatingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('child',), name='unique_child_assignment'),
        ),
    ]
