# Generated by Django 5.1.4 on 2025-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0015_add_registry_claim_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='gift_claimed_enabled',
            field=models.BooleanField(default=True, help_text='Notify when a guest claims a gift from the registry'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('todo_due_soon', 'Todo Due Soon (30 min)'), ('todo_due_now', 'Todo Due Now'), ('todo_overdue', 'Todo Overdue'), ('todo_reminder', 'Todo Reminder'), ('todo_completed', 'Todo Completed'), ('rsvp_accepted', 'RSVP Accepted'), ('rsvp_declined', 'RSVP Declined'), ('rsvp_pending', 'RSVP Pending Reminder'), ('gift_claimed', 'Gift Claimed'), ('gift_unclaimed', 'Gift Unclaimed'), ('rsvp', 'RSVP Update'), ('payment', 'Payment'), ('task', 'Task'), ('vendor', 'Vendor'), ('team', 'Team'), ('guest', 'Guest'), ('system', 'System'), ('reminder', 'Reminder')], max_length=20),
        ),
    ]
