# Generated by Django 5.1.4 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0018_seed_vendor_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='primary_image_url',
            field=models.URLField(blank=True, help_text='Main vendor image URL (external link)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main vendor image/logo (file upload)', null=True, upload_to='vendors/images/'),
        ),
    ]
