# Generated by Django 5.1.4 on 2025-12-04 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0020_add_image_and_allergens_to_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Access Code')),
                ('name', models.CharField(help_text="A friendly name to identify this access (e.g., 'Main Restaurant')", max_length=100, verbose_name='Token Name')),
                ('restaurant_name', models.CharField(blank=True, max_length=200, verbose_name='Restaurant Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('can_manage_tables', models.BooleanField(default=True, help_text='Allow creating/editing table names, capacity, and location', verbose_name='Can Manage Tables')),
                ('can_manage_meals', models.BooleanField(default=True, help_text='Allow creating/editing menu items and allergens', verbose_name='Can Manage Meals')),
                ('can_view_guest_count', models.BooleanField(default=True, help_text='Allow viewing total confirmed guest count (no names/details)', verbose_name='Can View Guest Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True, verbose_name='Expires At')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Access Count')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this access token')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_access_tokens', to='wedding_planner.wedding')),
            ],
            options={
                'verbose_name': 'Restaurant Access Token',
                'verbose_name_plural': 'Restaurant Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
