# Generated by Django 5.1.4 on 2025-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0021_add_restaurant_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealchoice',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason provided by service provider if request is declined', verbose_name='Decline Reason'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text='Status of this meal request (pending approval from service provider)', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the status was last updated by service provider', null=True, verbose_name='Status Updated At'),
        ),
    ]
