# Generated by Django 5.1.4 on 2025-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0022_add_meal_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealchoice',
            name='client_decline_reason',
            field=models.TextField(blank=True, help_text='Reason provided by client if they decline', verbose_name='Client Decline Reason'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='client_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text="Client's approval status for this meal", max_length=20, verbose_name='Client Status'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='client_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Client Status Updated At'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='created_by',
            field=models.CharField(choices=[('client', 'Couple/Client'), ('restaurant', 'Restaurant')], default='client', help_text='Who created this meal option', max_length=20, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='restaurant_decline_reason',
            field=models.TextField(blank=True, help_text='Reason provided by restaurant if they decline', verbose_name='Restaurant Decline Reason'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='restaurant_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text="Restaurant's approval status for this meal", max_length=20, verbose_name='Restaurant Status'),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='restaurant_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Restaurant Status Updated At'),
        ),
        migrations.AlterField(
            model_name='mealchoice',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason for decline (from whoever declined)', verbose_name='Decline Reason'),
        ),
        migrations.AlterField(
            model_name='mealchoice',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text='Overall status (pending until both approve)', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='mealchoice',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the status was last updated', null=True, verbose_name='Status Updated At'),
        ),
    ]
