# Generated by Django 5.1.4 on 2025-10-11 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("shopping", "Shopping"),
                            ("other", "Other"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
