# Generated by Django 5.1.4 on 2025-10-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_active',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
