# Generated by Django 5.1.4 on 2025-10-18 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wedding_planner",
            "0002_gender_remove_guestpartner_guest_delete_child_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "is_plus_one_coming",
                    models.BooleanField(
                        default=False, verbose_name="is plus one coming"
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="has children"),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("yes", "Yes"), ("pending", "Pending"), ("no", "No")],
                        default="pending",
                        max_length=10,
                        verbose_name="attendance status",
                    ),
                ),
                (
                    "user_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="user code",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest",
                "verbose_name_plural": "guests",
                "indexes": [
                    models.Index(fields=["email"], name="wedding_pla_email_576ede_idx"),
                    models.Index(
                        fields=["last_name"], name="wedding_pla_last_na_cf66b0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField(null=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding_planner.guest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
