# Generated by Django 5.1.4 on 2025-11-06 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_planner", "0003_guest_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestsMax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_allowed", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name": "guest max",
                "verbose_name_plural": "guests max",
            },
        ),
    ]
