# Generated by Django 5.1.4 on 2025-11-29 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_planner", "0007_documentfolder_document_donotplaysong_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_budget",
                to="wedding_planner.weddingevent",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_checklist",
                to="wedding_planner.weddingevent",
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dietaryrestriction",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Restriction Name"),
        ),
        migrations.AlterField(
            model_name="giftregistry",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_registry",
                to="wedding_planner.weddingevent",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.PositiveIntegerField(verbose_name="Table Number"),
        ),
        migrations.AlterField(
            model_name="weddingteam",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_team",
                to="wedding_planner.weddingevent",
            ),
        ),
        migrations.AlterField(
            model_name="weddingwebsite",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_website",
                to="wedding_planner.weddingevent",
            ),
        ),
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner1_name",
                    models.CharField(max_length=100, verbose_name="Partner 1 Name"),
                ),
                (
                    "partner2_name",
                    models.CharField(max_length=100, verbose_name="Partner 2 Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique URL-friendly identifier for this wedding",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "wedding_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Wedding Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "is_website_public",
                    models.BooleanField(
                        default=False, verbose_name="Public Wedding Website"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#e11d48",
                        help_text="Primary color hex code",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#fda4af",
                        help_text="Secondary color hex code",
                        max_length=7,
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="Cover Image URL"),
                ),
                (
                    "public_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public code for guests to access the wedding website",
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wedding",
                "verbose_name_plural": "Weddings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="wedding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="wedding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="dietaryrestriction",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for global restriction available to all weddings",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dietary_restrictions",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for global templates available to all weddings",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="giftregistry",
            name="wedding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registry",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="mealchoice",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_choices",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="weddingevent",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="weddingteam",
            name="wedding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddField(
            model_name="weddingwebsite",
            name="wedding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="website",
                to="wedding_planner.wedding",
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                fields=("wedding", "email"), name="unique_email_per_wedding"
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("wedding", "table_number"), name="unique_table_per_wedding"
            ),
        ),
    ]
