# Generated by Django 5.1.4 on 2025-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0008_alter_budget_event_alter_budget_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('sister', 'Sister'), ('brother', 'Brother'), ('daughter', 'Daughter'), ('son', 'Son'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('cousin', 'Cousin'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('great_aunt', 'Great Aunt'), ('great_uncle', 'Great Uncle'), ('second_cousin', 'Second Cousin'), ('cousin_once_removed', 'Cousin Once Removed'), ('distant_relative', 'Distant Relative')], help_text='Only applicable if guest type is Family', max_length=30, null=True, verbose_name='Family Relationship'),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('coworker', 'Coworker'), ('neighbor', 'Neighbor'), ('other', 'Other')], default='friend', max_length=20, verbose_name='Guest Type'),
        ),
        migrations.AddField(
            model_name='guest',
            name='relationship_tier',
            field=models.CharField(blank=True, choices=[('first', '1st Tier (Immediate Family)'), ('second', '2nd Tier (Close Extended)'), ('third', '3rd Tier (Distant Relatives)')], help_text='Closeness tier for family members', max_length=10, null=True, verbose_name='Relationship Tier'),
        ),
    ]
