# Generated by Django 5.1.4 on 2025-11-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0011_seatingassignment_attendee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_category',
            field=models.CharField(blank=True, choices=[('', 'No specific category'), ('family', 'Family'), ('family_tier_first', 'Family - 1st Tier (Immediate)'), ('family_tier_second', 'Family - 2nd Tier (Close Extended)'), ('family_tier_third', 'Family - 3rd Tier (Distant)'), ('friend', 'Friends'), ('coworker', 'Coworkers'), ('neighbor', 'Neighbors'), ('vip', 'VIP'), ('kids', 'Kids Table')], default='', help_text='Category of guests for this table (used for auto-assign)', max_length=30, verbose_name='Guest Category'),
        ),
    ]
