# Generated by Django 5.1.4 on 2025-12-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_wedding', '0001_initial'),
        ('wedding_planner', '0012_add_table_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wedding_planner.guest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todo_list_wedding.todo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wedding_planner.wedding'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='rsvp_accepted_enabled',
            field=models.BooleanField(default=True, help_text='Notify when guest accepts invitation'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='rsvp_declined_enabled',
            field=models.BooleanField(default=True, help_text='Notify when guest declines invitation'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='todo_due_now_enabled',
            field=models.BooleanField(default=True, help_text='Notify when todo is due'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='todo_due_soon_enabled',
            field=models.BooleanField(default=True, help_text='Notify 30 minutes before todo is due'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='todo_overdue_enabled',
            field=models.BooleanField(default=True, help_text='Notify when todo becomes overdue'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='wedding_planner.wedding'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('todo_due_soon', 'Todo Due Soon (30 min)'), ('todo_due_now', 'Todo Due Now'), ('todo_overdue', 'Todo Overdue'), ('todo_reminder', 'Todo Reminder'), ('rsvp_accepted', 'RSVP Accepted'), ('rsvp_declined', 'RSVP Declined'), ('rsvp_pending', 'RSVP Pending Reminder'), ('rsvp', 'RSVP Update'), ('payment', 'Payment'), ('task', 'Task'), ('vendor', 'Vendor'), ('team', 'Team'), ('guest', 'Guest'), ('system', 'System'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'wedding')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='wedding_pla_user_id_f360c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['wedding', '-created_at'], name='wedding_pla_wedding_986713_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='wedding_pla_notific_fb8454_idx'),
        ),
    ]
