# Generated by Django 5.1.4 on 2025-12-01 05:43

import apps.wedding_planner.models.registry_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0014_add_todo_completed_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registryitem',
            options={'ordering': ['display_order', '-priority', '-created_at'], 'verbose_name': 'Registry Item', 'verbose_name_plural': 'Registry Items'},
        ),
        migrations.AddField(
            model_name='giftregistry',
            name='allow_anonymous_claims',
            field=models.BooleanField(default=False, help_text='Allow claiming without guest code'),
        ),
        migrations.AddField(
            model_name='giftregistry',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show registry to guests'),
        ),
        migrations.AddField(
            model_name='giftregistry',
            name='show_prices',
            field=models.BooleanField(default=True, help_text='Show item prices to guests'),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('living_room', 'Living Room'), ('dining', 'Dining'), ('garden', 'Garden'), ('electronics', 'Electronics'), ('experiences', 'Experiences'), ('honeymoon', 'Honeymoon'), ('home_decor', 'Home Decor'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='claim_message',
            field=models.TextField(blank=True, help_text='Optional message from the guest who claimed the item'),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Guest who claimed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_registry_items', to='wedding_planner.guest'),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this item to guests'),
        ),
        migrations.AddField(
            model_name='registryitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link to product page', max_length=500),
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (max 1MB)', upload_to='registry_items/', validators=[apps.wedding_planner.models.registry_model.validate_image_size]),
        ),
    ]
