# Generated by Django 5.1.4 on 2025-12-01 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0016_add_gift_notification_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vendors/gallery/')),
                ('image_type', models.CharField(choices=[('gallery', 'Gallery'), ('portfolio', 'Portfolio'), ('venue', 'Venue'), ('food', 'Food'), ('team', 'Team'), ('certificate', 'Certificate'), ('other', 'Other')], default='gallery', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vendor Image',
                'verbose_name_plural': 'Vendor Images',
                'ordering': ['-is_featured', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VendorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('package', 'Package'), ('service', 'Individual Service'), ('promo', 'Promotion'), ('bundle', 'Bundle Deal'), ('addon', 'Add-on')], default='package', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (for promos)', max_digits=12, null=True)),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('includes', models.JSONField(default=list, help_text='\n        List of included items/services. Format:\n        ["8 hours coverage", "2 photographers", "500 edited photos", "Online gallery"]\n        ')),
                ('excludes', models.JSONField(default=list, help_text='List of items NOT included')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Vendor Offer',
                'verbose_name_plural': 'Vendor Offers',
                'ordering': ['-is_featured', 'sort_order', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-is_featured', '-average_rating', 'sort_order', 'name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'ordering': ['-is_featured', 'sort_order', 'name'], 'verbose_name': 'Vendor Category', 'verbose_name_plural': 'Vendor Categories'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='accepts_credit_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='awards',
            field=models.TextField(blank=True, help_text='Awards and recognition'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='booking_status',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('booked', 'Fully Booked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Format: {"monday": {"open": "09:00", "close": "18:00", "closed": false}, ...}\n        '),
        ),
        migrations.AddField(
            model_name='vendor',
            name='currency',
            field=models.CharField(default='THB', max_length=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='deposit_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Required deposit percentage (e.g., 50)', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='insurance_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text="Comma-separated list (e.g., 'Thai, English, Chinese')", max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum days notice required for booking', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='licenses',
            field=models.TextField(blank=True, help_text='Business licenses, certifications'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='min_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='offers_payment_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main vendor image/logo', null=True, upload_to='vendors/images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_area',
            field=models.TextField(blank=True, help_text="Areas where vendor provides service (e.g., 'Bangkok, Phuket, Chiang Mai')"),
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tagline',
            field=models.CharField(blank=True, help_text="Short catchy description (e.g., 'Capturing your love story')", max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='category_type',
            field=models.CharField(choices=[('venue', 'Venue'), ('photography', 'Photography & Video'), ('catering', 'Food & Beverage'), ('beauty', 'Beauty & Wellness'), ('decor', 'Decor & Flowers'), ('entertainment', 'Entertainment'), ('planning', 'Planning & Coordination'), ('fashion', 'Fashion & Attire'), ('stationery', 'Stationery & Print'), ('transportation', 'Transportation'), ('officiant', 'Officiant & Legal'), ('gifts', 'Gifts & Favors'), ('accommodation', 'Accommodation'), ('honeymoon', 'Honeymoon & Travel'), ('other', 'Other Services')], default='other', help_text='Parent category type for grouping', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured categories shown first'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Sort order for display (lower = first). Backend handles sorting.'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for services', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for services', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name (lucide/heroicons) or emoji', max_length=50),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category', 'is_active'], name='wedding_pla_categor_1c37b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city', 'country'], name='wedding_pla_city_6a0864_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['-average_rating'], name='wedding_pla_average_8bd0aa_idx'),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wedding_planner.vendor'),
        ),
        migrations.AddField(
            model_name='vendoroffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wedding_planner.vendor'),
        ),
    ]
