# Generated by Django 5.1.4 on 2025-12-04 01:37

import apps.wedding_planner.models.meal_model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0019_add_primary_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealchoice',
            name='contains_allergens',
            field=models.JSONField(blank=True, default=list, help_text="List of allergens present in this meal (e.g., ['nuts', 'dairy', 'gluten'])"),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='image',
            field=models.ImageField(blank=True, help_text='Meal image (max 1MB, formats: jpg, jpeg, png, webp)', null=True, upload_to=apps.wedding_planner.models.meal_model.meal_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.wedding_planner.models.meal_model.validate_image_size]),
        ),
    ]
